/* Generated By:JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package com.example.dao;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 4;
  /** RegularExpression Id. */
  int EOL = 5;
  /** RegularExpression Id. */
  int Number = 6;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "\"+\"",
    "\";\"",
    "<Number>",
  };

}
